import {MapPin,AlertTriangle,MoreHorizontal,Info,Droplet,Leaf,Mountain,ChevronRight} from 'lucide-react'
import type {LucideIcon} from 'lucide-react'
import Ring from '../charts/Ring'
import {Factors} from './Explain'
import {sitesOf} from '../../data/mock'
import type {Spring,Site} from '../../types'
const IV:[Site['type'],string,string,LucideIcon,string][]=[['Contour trench','Contour trench','Suitable terrain detected',Mountain,'#D9722B'],['Recharge structure','Small recharge structure','Runoff concentration area',Droplet,'#168AAD'],['Vegetation treatment','Vegetation treatment','Land-cover opportunity',Leaf,'#0F6B57']]
export default function AnalysisPanel({s,onModal,onAssess,onRisk}:{s:Spring;onModal:(k:'why'|'evidence')=>void;onAssess:(x:Site)=>void;onRisk:()=>void}){
  const sites=sitesOf(s),warn=s.status.includes('validation')
  return <aside className="w-[380px] shrink-0 hidden xl:block overflow-y-auto card p-4 space-y-4">
    <div className="flex items-center gap-3"><MapPin className="text-wb" size={26}/><div className="flex-1"><h2 className="font-bold text-lg leading-tight">{s.name}</h2><p className="text-xs text-slate-500">Kumaon Himalaya</p></div><MoreHorizontal size={18}/></div>
    <div className="grid grid-cols-[auto_1fr_1fr] gap-3 items-center border-b border-[#d5e0d2] pb-3"><div className="flex items-center gap-2"><Ring v={s.prob}/><b className="text-sm leading-tight">Recharge<br/>probability</b></div>
      <div className="text-xs text-slate-500">Springshed<div className="text-lg font-semibold text-[#18332D]">{s.area} km²</div></div><div className="text-xs text-slate-500">Evidence quality<div className="text-lg font-semibold text-warn">{s.evidence}</div></div></div>
    <div className="flex items-center gap-2 text-xs"><AlertTriangle size={16} className="text-warn"/>Validation status<span className={`ml-auto px-2 py-1 rounded-full ${warn?'bg-amber-100 text-amber-800':'bg-green-100 text-green-800'}`}>{warn?'Field validation required':'Review recommended'}</span></div>
    <section><div className="flex items-center justify-between mb-2"><h3 className="font-bold text-sm flex items-center gap-1.5">Model explanation<Info size={13} className="text-slate-400"/></h3><button onClick={()=>onModal('why')} className="text-xs text-g font-medium">Why this prediction?</button></div><Factors p={s.prob}/><p className="text-[10px] text-slate-400 mt-1.5">Demo explanation values — not from a trained model.</p></section>
    <section className="rounded-lg bg-lg/70 p-3 text-xs"><h3 className="font-bold text-sm mb-1">Recharge hypothesis</h3><p className="text-slate-700">Rainfall infiltrating the upper eastern slope is likely contributing to groundwater feeding this spring through favorable geological structures.</p><div className="flex justify-between mt-2"><span>Confidence <b>{s.prob}%</b></span><span>Evidence <b>{s.evidence}</b></span><span>Validation <b>Required</b></span></div><button onClick={()=>onModal('evidence')} className="btn border border-g text-g mt-2 hover:bg-white">View evidence</button></section>
    <section><h3 className="font-bold text-xs tracking-wide mb-2">INTERVENTION OPPORTUNITIES</h3><div className="space-y-2">{IV.map(([t,n,d,I,c])=><div key={t} className="flex items-center gap-3 border border-[#d5e0d2] rounded-lg p-2.5 hover:shadow-md cursor-pointer" onClick={()=>onAssess(sites.find(x=>x.type===t)!)}><span className="w-10 h-10 rounded-lg grid place-items-center text-white" style={{background:c}}><I size={20}/></span><div className="flex-1"><b className="text-sm">{n}</b><p className="text-xs text-slate-500">{d}</p></div><span className="btn bg-g text-white flex items-center">Assess on field<ChevronRight size={13}/></span></div>)}</div></section>
    <section className="border border-red-200 rounded-lg p-3"><h3 className="text-[11px] font-bold tracking-wide text-bad flex items-center gap-1"><AlertTriangle size={14}/>RISK CONSTRAINTS</h3><div className="flex items-center gap-3 mt-1.5"><div className="flex-1"><b className="text-amber-700 bg-amber-50 px-2 py-0.5 rounded">Moderate</b><p className="text-[11px] text-slate-500 mt-1">Steep-slope and geological constraints require field assessment.</p></div><button onClick={onRisk} className="btn border border-g text-g">View risk map</button></div></section></aside>}
